### ISSUE TITLE
Cannot find module: model is not being resolved.

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/fake-data-generator#23]
**Describe the bug**
When the package is used as an npm dependency, models must be defined in `/models...`

```bash
Thrown:
{ Error: Cannot find module '/home/xxx/Documents/fake-data-generator/dist/models/authors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at getModel (/home/xxx/Documents/fake-data-generator/dist/lib/create-model.js:17:19)
    at createSingle (/home/xxx/Documents/fake-data-generator/dist/lib/create-model.js:25:15) code: 'MODULE_NOT_FOUND' }
```

**To Reproduce**
1. Create a model
2. Install `fake-data-generator` globally
3. Run `node`
4. Past [this code](https://github.com/Cambalab/fake-data-generator#2-use-it-in-your-own-module) and modify it according to your model name.
5. Error is thrown

**Expected behavior**
The executable should be able to read the `/models` directory to find the model that has been assigned to it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 9
-  Node: 10.16.3

**Additional context**
In future features, it would be nice the script does not depend on a `/models` directory and maybe rely on a single hardcoded model that works as input to create a single or many objects of the given model.

**Comment by jphetphoumy** [comment]
### Fix for the issue 

Hi ! I have done some testing with the **fake-data-generator** and find a fix for this issue you can take a look at the change I have made [here](https://github.com/Cambalab/fake-data-generator/compare/develop...jphetphoumy:fix/models-path)

### Eslint error
When I tried to commit I saw some **eslint** error : 

```
husky > pre-commit (node v11.14.0)

/root/Documents/developpment/fake-data-generator/lib/create-model.js
  15:54  error  'x' is defined but never used  no-unused-vars
  15:57  error  'i' is defined but never used  no-unused-vars

✖ 2 problems (2 errors, 0 warnings)

✘ ESLint failed!
husky > pre-commit hook failed (add --no-verify to bypass)
```

I made a fix for the error [here](https://github.com/Cambalab/fake-data-generator/commit/7fff2df4ca3dfba906c27859032abf2613879808)

Let me know if this solution is good for you and I will make a PR

**Comment by glmaljkovich** [comment]
Hi, @jphetphoumy I was working on that, but since we came up with the same solution @sgobotta you can go on and merge his PR.

**Comment by sgobotta** [comment]
@jphetphoumy feel free to open a PR. I checked your code and seems to work fine, though we still need to put our fixtures in a `/models` directory, That'll be covered in future issues : )
